//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTests.Domain.Entities
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Answer
    {
        public int ID { get; set; }

        [Required( ErrorMessage="აუცილებელი ველი")]
        [Display(Name="პასუხის ტექსტი")]
        public string Text { get; set; }

        [Display(Name = "სწორი/არასწორი")]
        public string IsRight { get; set; }

        public int QuestionId { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
