//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTests.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int ID { get; set; }
        
        [Required(ErrorMessage="აუცილებელი ველი")]
        [Display(Name="ქულა")]
        [Range(1,5,ErrorMessage="ქულა უნდა იყოს 1-დან 5-მდე")]
        public int Point { get; set; }

        [Required(ErrorMessage="აუცილებელი ველი")]
        [Display(Name="დრო პასუხის გასაცემად(წამებში)")]
        [Range(10,300,ErrorMessage="10 წამიდან 5 წუთამდე(300წამი)")]
        public int TimeForAnswer { get; set; }

        [Required(ErrorMessage = "აუცილებელი ველი")]
        [Display(Name="კითხვის ტექსტი")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }

        public int TestId { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Test Test { get; set; }
    }
}
