//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTests.Domain.Entities
{
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
    
    public partial class Test
    {
        public Test()
        {
            this.Questions = new HashSet<Question>();
            this.UserResults = new HashSet<UserResult>();
        }
    
        public int ID { get; set; }

        public int CategoryId { get; set; }

        [Required(ErrorMessage = "აუცილებელი ველი")]
        [Display(Name="ტესტის სახელი")]
        public string Name { get; set; }

        [Required(ErrorMessage="აუცილებელი ველი")]
        [Range(1,10,ErrorMessage="სირთულე უნდა იყოს 1-დან 10-მდე")]
        [Display(Name="სირთულე")]
        public int Level { get; set; }

        [Display(Name="აქტიური/წაშლილი")]
        public string IsActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<UserResult> UserResults { get; set; }
        [Display(Name="მაქსიმალური ქულა")]
        public int maxPoint { get { return validQuestions.Sum(q => q.Point); } }
        public IEnumerable<Question> validQuestions { get { return Questions.Where(q => q.Answers.Count() >= 2 && q.Answers.Count(a => a.IsRight == "Yes") < q.Answers.Count() && q.Answers.Count(a => a.IsRight == "Yes")>=1); } }

    }
}
