//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTests.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResult
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int TestId { get; set; }
        public System.DateTime TestTakenTime { get; set; }
        public int PointsEarned { get; set; }
        public int MaxPoint { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
